name: ci-dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  plan-and-smoke:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # OIDC
      contents: read

    env:
      TF_WORKING_DIR: terraform
      AWS_REGION: eu-west-2
      TF_VAR_stage: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::416162027738:role/url-dev-gha-plan":role/url-dev-gha-plan
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt/validate/init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform fmt -recursive -check
          terraform validate
          terraform init -input=false

      - name: Terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -no-color -var="stage=${{ env.TF_VAR_stage }}"

      
      - name: Smoke test (POST/GET)
        env:
          API_URL: ${{ secrets.DEV_API_URL }}   # set this in repo Settings → Secrets and variables → Actions
        run: |
          bash verify.sh "$API_URL"
