name: deploy-prod

on:
  workflow_dispatch:

env:
  TF_WORKING_DIR: terraform
  AWS_REGION: eu-west-2
  TF_VAR_stage: prod
  TF_IN_AUTOMATION: "1"

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::416162027738:role/url-prod-gha-apply
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform init (prod backend)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false -upgrade -backend-config=backend-prod.hcl
      - name: Terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate
      - name: Terraform plan (prod)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -no-color -var="stage=${{ env.TF_VAR_stage }}"

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: prod   # require approval in GitHub Environments
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::416162027738:role/url-prod-gha-apply
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform init (prod backend)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false -upgrade -backend-config=backend-prod.hcl
      - name: Terraform apply (prod)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -input=false -auto-approve -var="stage=${{ env.TF_VAR_stage }}"
      - name: Read API URL from state
        id: tfout
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: echo "api=$(terraform output -raw api_base_url)" >> "$GITHUB_OUTPUT"
      - name: Smoke test (POST/GET)
        env:
          API_URL: ${{ steps.tfout.outputs.api }}
        run: bash verify.sh "$API_URL"
